# Generated by Django 2.2.1 on 2019-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicsName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicsName', models.CharField(max_length=255)),
                ('SubTopic', models.ManyToManyField(to='app.SubTopic')),
            ],
        ),
    ]
