# Generated by Django 2.2.1 on 2019-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_topics_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
        migrations.AddField(
            model_name='topics',
            name='authors',
            field=models.ManyToManyField(to='app.Author'),
        ),
    ]
