# Generated by Django 2.2.1 on 2019-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190512_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='topics',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='topics',
            name='subTopic',
            field=models.ManyToManyField(to='app.SubTopic'),
        ),
    ]
