# Generated by Django 2.2.1 on 2019-05-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190512_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='topic',
            new_name='subName',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='subTopic',
        ),
        migrations.AddField(
            model_name='topics',
            name='sub',
            field=models.ManyToManyField(to='app.SubTopic'),
        ),
    ]
